name: Deployment Pipeline2

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install dependencies --no-audit --no-fund --no-optional
        run: npm install --no-audit --no-fund --no-optional
      - name: Build
        run: npm test
      - name: test
        run: npm test
      - name: Deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 
        with:
          heroku_api_key: HRKU-4d7444d0-c364-4750-a92e-e97902ddc4d1
          heroku_app_name: midu-ci-gh
          heroku_email: pablo.javier.torres.martinez@gmail.com

